
flowchart TD
    subgraph VMs[Environments]
        VM[Virtual Machines] --> |Agent| A1[Chimera]
        POD[Containers] --> |eBPF| A1[Chimera]
    end

    subgraph Agents[Data Collection Agents]
        A1[Chimera] -->|Collects| D1[Syscalls]
        A1[Chimera] -->|Collects| D2[Logs]
        A1[Chimera] -->|Collects| D3[Metrics]
        A1[Chimera] -->|Collects| D4[Network Packets]
    end

    subgraph Processing[Local Model Training]
        Parse[Parsing] --> Filter[Filtering]
        Filter[Filtering] --> Agg
        Agg[Aggregation] --> Norm[Normalization]
        Norm --> EnRich[Enrichment]
        EnRich --> Corr[Correlation]
    end

    subgraph Trust[Trust Inference Engine]
        TI1[Behavioral Anomalies]
        TI2[Signature Matches]
        TI3[Compliance Checks]
        TI4[Reputation Score]
        TI5[Resource Usage Patterns]
        TI1[Trust Indicator Generation]
        TI2[AI Trust Score Calculation]
    end

    subgraph Output[Threat Intelligence]
        IS1[CTI Generation]
        IS2[OpenCTI Integration]
        IS3[Threat Intelligence Sharing]
        TA[Threat Analysis]
        DB[(Threat Intelligence Database)]
        RPT[Reports & Alerts]
    end


    Agents -->|Raw Data| Parse
    Agents -->|Raw Data| Trust
    Corr -->|Sightings and Structured Data| Trust
    Trust -->|Trust Scores| TA
    TA -->|Store Indicators| DB
    TA -->|Generate| RPT

    style VM fill:#f9f9f9,stroke:#666
    style Agents fill:#f9f9f9,stroke:#666
    style Processing fill:#e6f3ff,stroke:#3399ff
    style Trust fill:#ffe6e6,stroke:#ff6666
    style Output fill:#e6ffe6,stroke:#33cc33