"""Sigma-rules DB model

Revision ID: 82d2c9b369cb
Revises: 333bae8a6686
Create Date: 2025-04-17 16:06:21.914317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d2c9b369cb'
down_revision: Union[str, None] = '333bae8a6686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sigma_rule_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sigma_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigmarule_id', sa.String(), nullable=True),
    sa.Column('sigma_rule_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sigmarules_indexes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('SigmaRule_id', sa.Integer(), nullable=True),
    sa.Column('IndexName', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('SQL_Query', sa.Text(), nullable=True),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_executed_at', sa.DateTime(), nullable=True),
    sa.Column('next_execution_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['SigmaRule_id'], ['sigma_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sigma_rule_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SigmaRule_index_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('num_rows', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['SigmaRule_index_id'], ['sigmarules_indexes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sigmarules_indexes_fields_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SigmaRule_index_id', sa.Integer(), nullable=True),
    sa.Column('SigmaRule_FieldName', sa.String(), nullable=True),
    sa.Column('Index_FieldName', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['SigmaRule_index_id'], ['sigmarules_indexes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sigma_rule_execution_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('result_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['sigma_rule_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sigma_rule_execution_results')
    op.drop_table('sigmarules_indexes_fields_map')
    op.drop_table('sigma_rule_executions')
    op.drop_table('sigmarules_indexes')
    op.drop_table('sigma_rules')
    op.drop_table('sigma_rule_source')
    # ### end Alembic commands ###
